[Backport] COMP: Fix linux build ensuring curl library is install in "lib" directory
Cherry picked from commit Slicer/Slicer@02c06341b4

This commit fixes the following error:

  error: '/work/Preview/Slicer-0-build/curl-install/lib/libcurl.a', needed by 'bin/libRemoteIO.so', missing and no known rule to make it

It fixes a regression originally introduced in Slicer/Slicer@128fb86dd1 (ENH: Update
curl from 7.34 to 7.70)

See issue 5000 and PR-4992